install.packages("mvtnorm")
install.packages("mclust")
install.packages("flexmix")
install.packages("prabclus")
install.packages("diptest")
install.packages("robustbase")
install.packages("kernlab")
install.packages("trimcluster")
install.packages("fpc")
install.packages("factoextra")
install.packages("nloptr")
install.packages("RColorBrewer")
#For R 3.5.2
install.packages("circlize")
install.packages("GetoptLong")
install.packages("colorspace")
install.packages("RColorBrewer")
install.packages("GlobalOptions")
install.packages("devtools")
devtools::install_github("jokergoo/ComplexHeatmap",ref = 1.99.4)
#if (!requireNamespace("BiocManager", quietly = TRUE))
#  install.packages("BiocManager")
#BiocManager::install("ComplexHeatmap")
install.packages("here")
install.packages("tidyr")
install.packages("stringr")
install.packages("gplots")
install.packages("knitr")
install.packages("readr")
install.packages("readxl")


#packageurl <- "https://cran.r-project.org/src/contrib/Archive/mvtnorm/mvtnorm_1.0-8.tar.gz"
#install.packages(packageurl, repos=NULL, type="source")
#install.packages("devtools")
#devtools::install_github("jokergoo/ComplexHeatmap")
#install.packages("packrat")
#install.packages("dplyr")
#install.packages("purrr")
#install.packages("tibble")
#install.packages("ggpubr")
#install.packages("ggplot2")
#install.packages("ggrepel")
#install.packages("cowplot")
#install.packages("ggsignif")
#install.packages("circlize")