packageurl <- "https://cran.r-project.org/src/contrib/Archive/mvtnorm_1.0-9.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
install.packages("mclust")
install.packages("flexmix")
install.packages("prabclus")
install.packages("diptest")
install.packages("robustbase")
install.packages("kernlab")
install.packages("trimcluster")
packageurl <- "https://cran.r-project.org/src/contrib/Archive/fpc/fpc_2.1-11.1.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
install.packages("factoextra")
install.packages("nloptr")
install.packages("devtools")
devtools::install_github("jokergoo/ComplexHeatmap")
install.packages("packrat")
install.packages("here")
#install.packages("dplyr")
install.packages("tidyr")
#install.packages("purrr")
install.packages("stringr")
#install.packages("tibble")
install.packages("gplots")
install.packages("RColorBrewer")
#install.packages("ggpubr")
#install.packages("ggplot2")
#install.packages("ggrepel")
#install.packages("cowplot")
install.packages("circlize")
install.packages("knitr")
#install.packages("ggsignif")
install.packages("readr")
install.packages("readxl")